FROM python:3
 
WORKDIR /home/shai/Documents/backery/bakery-01/ex5
 
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
 
COPY . .
 
CMD ["gunicorn", "-w 4", "-b", "0.0.0.0:8000", "main:app"]

