
version: '3.9'

services:
  api:
    build: ./app/
    depends_on:
      - db
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    networks:
      - bakery 
    ports:
      - 5000:5000
    restart: always

  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - bakery
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  bakery:
    ipam:
      driver: bakery 
      config:
      - subnet: 172.31.32.0/20
        gateway: 172.31.32.1
