version: "3.8"
services:
  web:
    depends_on:
      - postgres
    build: .
    volumes:
      - /usr/src/app
      - ./shared-volume:/upvol
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      DB_URL: postgresql://admin:password@localhost:5432/db
  postgres:
    image: "postgres:9.6"
    environment:
      POSTGRES_DB: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data:delegated"
      - ./shared-volume:/upvol
    ports:
      - "5432:5432"
networks:
  default:
      name: bakery
volumes:
  shared-volume:
