pipeline { 
    agent any
    stages {
        stage('Build') { 
            steps {
	      script {
	       docker.build("microblog-image")
	       docker.image('microblog-image').run('-p 8000:5000')
                  }
            }
	}
                        }
        post {
            success {
                echo "Pipeline ran successfuly! :)"
        }
	    failure {
		 echo "Pipeline has failed..."
		    }
	}
	 }

